set bg=dark
set ts=4
set sw=4
set tw=80
set cc=80
set number

set encoding=utf-8

set ignorecase
set ruler
syntax on
filetype on 
filetype plugin on
filetype indent on

set hlsearch
set incsearch
set mouse=a

execute pathogen#infect()
