set bg=dark
set ts=4
set sw=4
set tw=80
set cc=80
set number

set encoding=utf-8

set ignorecase
set ruler
syntax on
filetype on 
filetype plugin on
filetype indent on

set hlsearch
set incsearch
set mouse=a

set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=2         "this is just what i use

execute pathogen#infect()
